### ISSUE TITLE
Disable rTorrent to start at boot

### ISSUE THREAD

**Issue by Matheeew** [dannyti/sboxsetup#18]
Hello, thanks for an awesome script, the only thing bothering me is that rTorrent is automatically starting at boot, how do I disable this? Many thanks.

**Comment by dannyti** [comment]
Why is it bothering you ? As a seedbox , it must start at boot. Especially in cases of any kind of crash or power disruption at data centre. 

However, if you still plan to disable rtorrent starting at boot; you can check crontab entries and disable the @reboot entry. Rtorrent will still start since there is a check for rtorrent running every 10 mins, so you might want to remove that crontab entry as well.

**Comment by Matheeew** [comment]
My disks are encrypted and the need to be mounted manually efter every reboot, if rTorrent starts automatically the torrents wont find the files. Where is the crontab-file located and what's the entry called that restarts rtorrent every 10 minutes? Thanks!

**Comment by dannyti** [comment]
crontab -e

and delete the relevant entries.

**Comment by Matheeew** [comment]
I ran "sudo crontab -e" and removed the entries and rebooted, rTorrent does still start at boot though?

**Comment by Matheeew** [comment]
I also did "crontab -e" without sudo and deleted those entries as well
